!
!
service integrated-vtysh-config
!
interface eth0
 ip address 192.172.192.1/30
 ipv6 nd suppress-ra
!
interface eth1
 ip address 192.172.0.6/30
 ipv6 nd suppress-ra
!
interface eth2
 ip address 192.172.0.14/30
 ipv6 nd suppress-ra
!
interface lo
!
router ospf
 ospf router-id 192.172.192.1
 network 192.172.0.4/30 area 0.0.0.0
 network 192.172.0.12/30 area 0.0.0.0
 network 192.172.192.0/30 area 0.0.0.2
!
ip forwarding
ipv6 forwarding
!
line vty
!
end
