!
!
service integrated-vtysh-config
!
interface eth0
 ip address 192.172.0.2/30
 ipv6 nd suppress-ra
!
interface eth1
 ip address 192.172.0.5/30
 ipv6 nd suppress-ra
!
interface eth2
 ip address 192.172.0.9/30
 ipv6 nd suppress-ra
!
interface lo
!
router ospf
 ospf router-id 192.172.0.2
 network 192.172.0.0/30 area 0.0.0.1
 network 192.172.0.4/30 area 0.0.0.0
 network 192.172.0.8/30 area 0.0.0.0
!
ip forwarding
ipv6 forwarding
!
line vty
!
end
